# Controller generated by Typus, use it to extend admin functionality.
class Admin::UserDetailsController < Admin::MasterController

=begin

  ##
  # You can overwrite and extend Admin::MasterController with your methods.
  #
  # Actions have to be defined in <tt>config/typus/application.yml</tt>:
  #
  #   UserDetail:
  #     actions:
  #       index: custom_action
  #       edit: custom_action_for_an_item
  #
  # And you have to add permissions on <tt>config/typus/application_roles.yml</tt> 
  # to have access to them.
  #
  #   admin:
  #     UserDetail: create, read, update, destroy, custom_action
  #
  #   editor:
  #     UserDetail: create, read, update, custom_action_for_an_item
  #

  def index
  end

  def custom_action
  end

  def custom_action_for_an_item
  end

=end

  def export
    @user_details = UserDetail.all
    
    respond_to do | format |
      format.csv { send_data @user_details.to_csv, :filename => "user_details_#{ Time.now.strftime( "%m-%d-%Y_%I:%M_%p" ) }.csv"  }
    end
  end

end
