# Typus Models Configuration File
#
# Use the README file on the same folder as this file as a reference to
# customize this file to your needs.

PostAttachment:
  fields:
    list: caption, attachment_file_name, post
    form: caption, oembed, code, attachment_file_name, post
    show: id, caption, oembed, code, attachment_file_name, created_at, updated_at, post
  actions:
    index:
    edit:
  order_by:
  relationships: post
  filters:
  search:
  application: Posts
  description:

