# Typus Models Configuration File
#
# Use the README file on the same folder as this file as a reference to
# customize this file to your needs.

OrganizationMember:
  fields:
    list: user, organization, is_active
    form: user, organization, is_active
    show: id, user, organization, is_active, created_at, updated_at
  actions:
    index:
    edit:
  order_by:
  relationships: organizations, users
  filters:
  search:
  application: Promos
  description:

