# Typus Roles Configuration File
#
# In this file you can configure the actions available for each of your 
# models on the application.
#
#     admin:
#       Post: create, read, update, delete
#       Category: create, read, update, delete
#
#     editor:
#       Post: create, read, update
#       Category: read, update
#
# You can also define `resources` which are not related to a model, 
# for example to control MemCached or see the Starling queue statistics.
#
#     admin:
#      Starling: index
#      MemCached: index, cleanup
#

admin:
  Ad: create, read, update, delete
  CachedBlogrollFeed: create, read, update, delete
  Comment: create, read, update, delete
  EmailBlast: create, read, update, delete
  EmailBlastTemplate: create, read, update, delete
  Event: create, read, update, delete
  Hobby: create, read, update, delete
  Interest: create, read, update, delete
  InterestLine: create, read, update, delete
  InterestPoint: create, read, update, delete
  Map: create, read, update, delete
  MapIcon: create, read, update, delete
  MapLayer: create, read, update, delete
  Organization: create, read, update, delete
  OrganizationMember: create, read, update, delete
  Page: create, read, update, delete
  Post: create, read, update, delete
  PostAttachment: create, read, update, delete
  PostType: create, read, update, delete
  Promo: create, read, update, delete
  BlogrollFeed: create, read, update, delete
  SiteOption: create, read, update, delete
  Suggestion: create, read, update, delete
  Tweet: create, read, update, delete
  User: create, read, update, delete, export
  UserDetail: create, read, update, delete, export
  UserHobby: create, read, update, delete
  UserInterest: create, read, update, delete
  UserLocation: create, read, update, delete
  UserWirelessProfile: create, read, update, delete
  WirelessCarrier: create, read, update, delete